twig:
    default_path: '%kernel.project_dir%/templates'
knp_paginator:
    template:
        pagination:
            '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates' 


when@test:
    twig:
        strict_variables: true
