controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

check_trick_name:
    path: /check-trick-name
    controller: App\Controller\TricksController::checkTrickName
    methods: [GET, POST]
